name: flutter_bluetooth_plus
description: Flutter plugin that allows to find bluetooth devices & send raw bytes data
version: 0.1.16
homepage: https://github.com/hoichong/flutter_bluetooth_plus

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.19.5"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.1.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.15 #^1.0.0
  json_serializable: 6.9.4 #^4.1.4

flutter:
  plugin:
    platforms:
      android:
        package: com.tablemi.flutter_bluetooth_plus
        pluginClass: FlutterBluetoothBasicPlugin
      ios:
        pluginClass: FlutterBluetoothBasicPlugin
